#! /bin/bash

exiting () {
    # create file and append build date
    filename="docker_build"
    now=$(date)
    touch $filename
    echo "$now $1" >> $filename
    if [ $1 != "attempting_building_image" ]; then
        echo "exiting script..."
        exit 1
    fi
}

cd `dirname $0`

arch="`uname -m`"
tag=
platform=
while test "$#" -ne 0; do
    if test "$1" = "-a" -o "$1" = "--arm" -o "$1" = "--arm64"; then
        if test "`arch`" = "arm64" -o "`arch`" = "aarch64"; then
            platform=linux/arm64
            shift
        else
            echo "\`csc412-build-docker --arm\` only works on ARM64 hosts" 1>&2
            exiting "only works on ARM64 hosts"
        fi
    elif test "$1" = "-x" -o "$1" = "--x86-64" -o "$1" = "--x86_64" -o "$1" = "--amd64"; then
        platform=linux/amd64
    else
        armtext=
        if test "`arch`" = "arm64" -o "`arch`" = "aarch64"; then
            armtext=" [-a|--arm] [-x|--x86-64]"
        fi
        echo "Usage: csc412-build-docker$armtext" 1>&2
        exiting "Incorrect Usage: csc412-build-docker"
    fi
done

if test -z "$platform" -a \( "$arch" = "arm64" -o "$arch" = "aarch64" \); then
    platform=linux/arm64
elif test -z "$platform"; then
    platform=linux/amd64
fi
if test -z "$tag" -a "$platform" = linux/arm64; then
    tag=csc412:arm64
elif test -z "$tag"; then
    tag=csc412:latest
fi
if test $platform = linux/arm64; then
    exiting "attempting_building_image"
    exec docker build -t "$tag" -f Dockerfile.arm64 --platform linux/arm64 .
    exiting "docker build arm64"
else
    exiting "attempting_building_image"
    exec docker build -t "$tag" -f Dockerfile --platform linux/amd64 .
    exiting "docker build linux"
fi

exiting "end of file..."
